## 데이터 분석 프로세스

In [1]:
import requests

In [2]:
url = 'https://github.com/wikibook/python-for-data-analysis-rev/raw/master/readme.txt'

In [3]:
r = requests.get(url)

In [4]:
r

<Response [200]>

In [5]:
file_name = 'C:/ex/py/pyPrj1/myPyCode/data/readme.txt'

In [6]:
with open(file_name, 'wb') as f:
    f.write(r.content)

In [7]:
import os

In [8]:
os.path.isfile(file_name) 

True

In [9]:
!type C:\ex\py\pyPrj1\myPyCode\data\missing_data_test.csv

연도,제품1,제품2,제품3,제품4
2015,250,150,,
2016,200,160,170,
2017,150,200,100,150
2018,120,230,130,170
2019,,250,140,


In [10]:
import pandas as pd

In [66]:
data_file = "C:/ex/py/pyPrj1/myPyCode/data/missing_data_test.csv"

In [72]:
df = pd.read_csv(data_file, encoding='cp949')

In [73]:
df

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    NaN    NaN
1  2016  200.0  160  170.0    NaN
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019    NaN  250  140.0    NaN

In [14]:
type(df)

pandas.core.frame.DataFrame

In [15]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [16]:
df.iloc[0]

연도     2015.0
제품1     250.0
제품2     150.0
제품3       NaN
제품4       NaN
Name: 0, dtype: float64

In [17]:
type(df.iloc[0]) #Series란 인덱스가 있는 배열

pandas.core.series.Series

In [18]:
df.iloc[0].index

Index(['연도', '제품1', '제품2', '제품3', '제품4'], dtype='object')

In [19]:
df.연도

0    2015
1    2016
2    2017
3    2018
4    2019
Name: 연도, dtype: int64

In [20]:
df['연도']

0    2015
1    2016
2    2017
3    2018
4    2019
Name: 연도, dtype: int64

In [21]:
df.iloc[2,]

연도     2017.0
제품1     150.0
제품2     200.0
제품3     100.0
제품4     150.0
Name: 2, dtype: float64

In [22]:
df.iloc[2:4,]

연도    제품1  제품2    제품3    제품4
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0

In [23]:
df.iloc[2:4,2:4]

제품2    제품3
2  200  100.0
3  230  130.0

In [24]:
df.iloc[0:3,3:5]

제품3    제품4
0    NaN    NaN
1  170.0    NaN
2  100.0  150.0

In [25]:
#help(df.set_index)

In [26]:
df.set_index('연도')

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [27]:
df=df.set_index('연도')

In [31]:
#df_index=df.set_index('연도')

In [32]:
df_index=df

In [29]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [33]:
df_index

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [34]:
df.loc[2015,]

제품1    250.0
제품2    150.0
제품3      NaN
제품4      NaN
Name: 2015, dtype: float64

In [35]:
df.loc[2015,'제품3']

nan

In [36]:
df.loc[[2015,2016,2017],['제품3','제품4']]

제품3    제품4
연도                
2015    NaN    NaN
2016  170.0    NaN
2017  100.0  150.0

In [37]:
df.loc[[2015,2017],['제품3','제품4']]

제품3    제품4
연도                
2015    NaN    NaN
2017  100.0  150.0

In [38]:
df.describe()

제품1         제품2         제품3         제품4
count    4.000000    5.000000    4.000000    2.000000
mean   180.000000  198.000000  135.000000  160.000000
std     57.154761   43.243497   28.867513   14.142136
min    120.000000  150.000000  100.000000  150.000000
25%    142.500000  160.000000  122.500000  155.000000
50%    175.000000  200.000000  135.000000  160.000000
75%    212.500000  230.000000  147.500000  165.000000
max    250.000000  250.000000  170.000000  170.000000

In [39]:
df.loc[2017]

제품1    150.0
제품2    200.0
제품3    100.0
제품4    150.0
Name: 2017, dtype: float64

In [40]:
df.loc[2017].values

array([150., 200., 100., 150.])

In [41]:
df.loc[2017].index

Index(['제품1', '제품2', '제품3', '제품4'], dtype='object')

In [42]:
#평균

In [43]:
(150+200+100+150)/4

150.0

In [44]:
df.제품2

연도
2015    150
2016    160
2017    200
2018    230
2019    250
Name: 제품2, dtype: int64

In [45]:
import numpy as np

In [46]:
avg=np.mean(df.제품2)

In [47]:
avg

198.0

In [48]:
df.제품2.values

array([150, 160, 200, 230, 250], dtype=int64)

In [49]:
# 편차(deviation)

In [50]:
deviation=avg-df.제품2.values

In [51]:
deviation

array([ 48.,  38.,  -2., -32., -52.])

In [52]:
deviation**2

array([2304., 1444.,    4., 1024., 2704.])

In [53]:
df.제품2.var()

1870.0

In [54]:
np.sqrt(df.제품2.var())

43.243496620879306

In [55]:
# 분산에 제곱근 -> 표준편차(Standard Deviation)

In [56]:
np.sum(deviation**2)/4

1870.0

In [57]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [58]:
df.isnull()

제품1    제품2    제품3    제품4
연도                              
2015  False  False   True   True
2016  False  False  False   True
2017  False  False  False  False
2018  False  False  False  False
2019   True  False  False   True

In [59]:
df.isnull().sum()

제품1    1
제품2    0
제품3    1
제품4    3
dtype: int64

In [60]:
#help(df.drop)

In [61]:
df.drop(index=[2019])

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [62]:
df=df.drop(index=[2019])

In [63]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [69]:
df

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    NaN    NaN
1  2016  200.0  160  170.0    NaN
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019    NaN  250  140.0    NaN

In [70]:
df2=df_index.drop(index=[2019])

In [71]:
df2

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [74]:
df3=df_index.drop(columns=['제품3','제품4'])

In [75]:
df3

제품1  제품2
연도              
2015  250.0  150
2016  200.0  160
2017  150.0  200
2018  120.0  230
2019    NaN  250

In [76]:
df_copy=df.copy()

In [77]:
df_copy

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    NaN    NaN
1  2016  200.0  160  170.0    NaN
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019    NaN  250  140.0    NaN

In [78]:
df_copy.dropna()

연도    제품1  제품2    제품3    제품4
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0

In [79]:
df_copy2=df.copy()

In [80]:
df_copy2

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    NaN    NaN
1  2016  200.0  160  170.0    NaN
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019    NaN  250  140.0    NaN

In [81]:
df_copy2.dropna(axis=1)

연도  제품2
0  2015  150
1  2016  160
2  2017  200
3  2018  230
4  2019  250

In [82]:
df_copy2_index=df_copy2.set_index('연도')

In [83]:
df_copy2_index

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [84]:
df_copy2_index.dropna(axis=1, subset=[2015])

제품1  제품2
연도              
2015  250.0  150
2016  200.0  160
2017  150.0  200
2018  120.0  230
2019    NaN  250

In [85]:
df_copy2_index.dropna(axis=1, subset=[2016,2019])

제품2    제품3
연도              
2015  150    NaN
2016  160  170.0
2017  200  100.0
2018  230  130.0
2019  250  140.0

In [86]:
df

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    NaN    NaN
1  2016  200.0  160  170.0    NaN
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019    NaN  250  140.0    NaN

In [87]:
df.fillna(0)

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    0.0    0.0
1  2016  200.0  160  170.0    0.0
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019    0.0  250  140.0    0.0

In [88]:
df

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    NaN    NaN
1  2016  200.0  160  170.0    NaN
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019    NaN  250  140.0    NaN

In [89]:
df.fillna(method='bfill')

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150  170.0  150.0
1  2016  200.0  160  170.0  150.0
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019    NaN  250  140.0    NaN

In [90]:
df

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    NaN    NaN
1  2016  200.0  160  170.0    NaN
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019    NaN  250  140.0    NaN

In [91]:
df.fillna(method='ffill')

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    NaN    NaN
1  2016  200.0  160  170.0    NaN
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019  120.0  250  140.0  170.0

In [92]:
df

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    NaN    NaN
1  2016  200.0  160  170.0    NaN
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019    NaN  250  140.0    NaN

In [93]:
values={'제품1':100,'제품4':400}
df.fillna(value=values)

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    NaN  400.0
1  2016  200.0  160  170.0  400.0
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019  100.0  250  140.0  400.0

In [94]:
df

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    NaN    NaN
1  2016  200.0  160  170.0    NaN
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019    NaN  250  140.0    NaN

## 데이터의 요약 및 재구성 
### 데이터의 구조 살펴보기

In [101]:
data_file1 = "C:/ex/py/pyPrj1/myPyCode/data/total_sales_data.csv"

In [102]:
df_sales = pd.read_csv(data_file1)

In [103]:
df_sales

매장명  제품종류 모델명  판매  재고
0   A  스마트폰  S1   1   2
1   A  스마트폰  S2   2   5
2   A    TV  V1   3   5
3   B  스마트폰  S2   4   6
4   B  스마트폰  S1   5   8
5   B    TV  V1   6   9
6   C  스마트폰  S2   2   4
7   C    TV  V1   3   6
8   C    TV  V2   7   9

In [104]:
df_sales.columns

Index(['매장명', '제품종류', '모델명', '판매', '재고'], dtype='object')

In [105]:
df_sales.모델명

0    S1
1    S2
2    V1
3    S2
4    S1
5    V1
6    S2
7    V1
8    V2
Name: 모델명, dtype: object

In [106]:
df_sales.describe()

판매        재고
count  9.000000  9.000000
mean   3.666667  6.000000
std    2.000000  2.345208
min    1.000000  2.000000
25%    2.000000  5.000000
50%    3.000000  6.000000
75%    5.000000  8.000000
max    7.000000  9.000000

In [107]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   매장명     9 non-null      object
 1   제품종류    9 non-null      object
 2   모델명     9 non-null      object
 3   판매      9 non-null      int64 
 4   재고      9 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 492.0+ bytes


In [108]:
df_sales['매장명'].value_counts()

매장명
A    3
B    3
C    3
Name: count, dtype: int64

In [109]:
df_sales.매장명.value_counts()

매장명
A    3
B    3
C    3
Name: count, dtype: int64

In [110]:
df_sales

매장명  제품종류 모델명  판매  재고
0   A  스마트폰  S1   1   2
1   A  스마트폰  S2   2   5
2   A    TV  V1   3   5
3   B  스마트폰  S2   4   6
4   B  스마트폰  S1   5   8
5   B    TV  V1   6   9
6   C  스마트폰  S2   2   4
7   C    TV  V1   3   6
8   C    TV  V2   7   9

In [111]:
df_sales.pivot_table(index=["매장명", "제품종류", "모델명"],
                     values =["판매","재고"], aggfunc='sum')

재고  판매
매장명 제품종류 모델명        
A   TV   V1    5   3
    스마트폰 S1    2   1
         S2    5   2
B   TV   V1    9   6
    스마트폰 S1    8   5
         S2    6   4
C   TV   V1    6   3
         V2    9   7
    스마트폰 S2    4   2

In [112]:
df_sales.pivot_table(index=["매장명"], columns = ["제품종류"],
                     values =["판매","재고"], aggfunc='sum')

재고       판매     
제품종류  TV 스마트폰  TV 스마트폰
매장명                   
A      5    7   3    3
B      9   14   6    9
C     15    4  10    2