## 데이터 분석 프로세스

In [270]:
import requests

In [271]:
url = 'https://github.com/wikibook/python-for-data-analysis-rev/raw/master/readme.txt'

In [272]:
r = requests.get(url)

In [273]:
r

<Response [200]>

In [274]:
file_name = 'C:/ex/py/pyPrj1/myPyCode/data/readme.txt'

In [275]:
with open(file_name, 'wb') as f:
    f.write(r.content)

In [276]:
import os

In [277]:
os.path.isfile(file_name) 

True

In [278]:
!type C:\ex\py\pyPrj1\myPyCode\data\missing_data_test.csv

연도,제품1,제품2,제품3,제품4
2015,250,150,,
2016,200,160,170,
2017,150,200,100,150
2018,120,230,130,170
2019,,250,140,


In [279]:
import pandas as pd

In [280]:
data_file = "C:/ex/py/pyPrj1/myPyCode/data/missing_data_test.csv"

In [281]:
df = pd.read_csv(data_file, encoding='cp949')

In [282]:
df

연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    NaN    NaN
1  2016  200.0  160  170.0    NaN
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019    NaN  250  140.0    NaN

In [283]:
type(df)

pandas.core.frame.DataFrame

In [284]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [285]:
df.iloc[0]

연도     2015.0
제품1     250.0
제품2     150.0
제품3       NaN
제품4       NaN
Name: 0, dtype: float64

In [105]:
type(df.iloc[0]) #Series란 인덱스가 있는 배열

pandas.core.series.Series

In [106]:
df.iloc[0].index

Index(['연도', '제품1', '제품2', '제품3', '제품4'], dtype='object')

In [107]:
df.연도

0    2015
1    2016
2    2017
3    2018
4    2019
Name: 연도, dtype: int64

In [108]:
df['연도']

0    2015
1    2016
2    2017
3    2018
4    2019
Name: 연도, dtype: int64

In [109]:
df.iloc[2,]

연도     2017.0
제품1     150.0
제품2     200.0
제품3     100.0
제품4     150.0
Name: 2, dtype: float64

In [110]:
df.iloc[2:4,]

연도    제품1  제품2    제품3    제품4
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0

In [111]:
df.iloc[2:4,2:4]

제품2    제품3
2  200  100.0
3  230  130.0

In [112]:
df.iloc[0:3,3:5]

제품3    제품4
0    NaN    NaN
1  170.0    NaN
2  100.0  150.0

In [113]:
#help(df.set_index)

In [114]:
df.set_index('연도')

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [157]:
df=df.set_index('연도')

KeyError: "None of ['연도'] are in the columns"

In [269]:
df_index=df.set_index('연도')

KeyError: "None of ['연도'] are in the columns"

In [117]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [118]:
df_index

NameError: name 'df_index' is not defined

In [156]:
df.index

Index([2015, 2016, 2017, 2018], dtype='int64', name='연도')

In [120]:
df.loc[2015,]

제품1    250.0
제품2    150.0
제품3      NaN
제품4      NaN
Name: 2015, dtype: float64

In [121]:
df.loc[2015,'제품3']

nan

In [122]:
df.loc[[2015,2016,2017],['제품3','제품4']]

제품3    제품4
연도                
2015    NaN    NaN
2016  170.0    NaN
2017  100.0  150.0

In [123]:
df.loc[[2015,2017],['제품3','제품4']]

제품3    제품4
연도                
2015    NaN    NaN
2017  100.0  150.0

In [124]:
df.describe()

제품1         제품2         제품3         제품4
count    4.000000    5.000000    4.000000    2.000000
mean   180.000000  198.000000  135.000000  160.000000
std     57.154761   43.243497   28.867513   14.142136
min    120.000000  150.000000  100.000000  150.000000
25%    142.500000  160.000000  122.500000  155.000000
50%    175.000000  200.000000  135.000000  160.000000
75%    212.500000  230.000000  147.500000  165.000000
max    250.000000  250.000000  170.000000  170.000000

In [125]:
df.loc[2017]

제품1    150.0
제품2    200.0
제품3    100.0
제품4    150.0
Name: 2017, dtype: float64

In [126]:
df.loc[2017].values

array([150., 200., 100., 150.])

In [127]:
df.loc[2017].index

Index(['제품1', '제품2', '제품3', '제품4'], dtype='object')

In [128]:
#평균

In [129]:
(150+200+100+150)/4

150.0

In [130]:
df.제품2

연도
2015    150
2016    160
2017    200
2018    230
2019    250
Name: 제품2, dtype: int64

In [131]:
import numpy as np

In [132]:
avg=np.mean(df.제품2)

In [133]:
avg

198.0

In [134]:
df.제품2.values

array([150, 160, 200, 230, 250], dtype=int64)

In [135]:
# 편차(deviation)

In [136]:
deviation=avg-df.제품2.values

In [137]:
deviation

array([ 48.,  38.,  -2., -32., -52.])

In [138]:
deviation**2

array([2304., 1444.,    4., 1024., 2704.])

In [139]:
df.제품2.var()

1870.0

In [140]:
np.sqrt(df.제품2.var())

43.243496620879306

In [141]:
# 분산에 제곱근 -> 표준편차(Standard Deviation)

In [142]:
np.sum(deviation**2)/4

1870.0

In [143]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [144]:
df.isnull()

제품1    제품2    제품3    제품4
연도                              
2015  False  False   True   True
2016  False  False  False   True
2017  False  False  False  False
2018  False  False  False  False
2019   True  False  False   True

In [145]:
df.isnull().sum()

제품1    1
제품2    0
제품3    1
제품4    3
dtype: int64

In [146]:
#help(df.drop)

In [147]:
df.drop(index=[2019])

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [148]:
df=df.drop(index=[2019])

In [149]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [150]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [151]:
df2=df_index.drop(index=[2019])

NameError: name 'df_index' is not defined

In [152]:
df2

NameError: name 'df2' is not defined

In [153]:
df3=df_index.drop(columns=['제품3','제품4'])

NameError: name 'df_index' is not defined

In [159]:
df3

NameError: name 'df3' is not defined

In [160]:
df_copy=df.copy()

In [161]:
df_copy

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [162]:
df_copy.dropna()

제품1  제품2    제품3    제품4
연도                            
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [163]:
df_copy2=df.copy()

In [164]:
df_copy2

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [165]:
df_copy2.dropna(axis=1)

제품1  제품2
연도              
2015  250.0  150
2016  200.0  160
2017  150.0  200
2018  120.0  230

In [166]:
df_copy2_index=df_copy2.set_index('연도')

KeyError: "None of ['연도'] are in the columns"

In [167]:
df_copy2_index

NameError: name 'df_copy2_index' is not defined

In [168]:
df_copy2_index.dropna(axis=1, subset=[2015])

NameError: name 'df_copy2_index' is not defined

In [169]:
df_copy2_index.dropna(axis=1, subset=[2016,2019])

NameError: name 'df_copy2_index' is not defined

In [170]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [171]:
df.fillna(0)

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    0.0    0.0
2016  200.0  160  170.0    0.0
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [172]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [173]:
df.fillna(method='bfill')

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150  170.0  150.0
2016  200.0  160  170.0  150.0
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [174]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [175]:
df.fillna(method='ffill')

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [176]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [177]:
values={'제품1':100,'제품4':400}
df.fillna(value=values)

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN  400.0
2016  200.0  160  170.0  400.0
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [178]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

## 데이터의 요약 및 재구성 
### 데이터의 구조 살펴보기